build:
		gcc main.c ./src/arithmetic/addition.c ./src/arithmetic/subtraction.c ./src/arithmetic/division.c ./src/arithmetic/multiplication.c ./src/calculator/validateinfix.c ./src/calculator/eval_infix.c ./src/calculator/precedence.c -o calculator

run:
		./calculator

clean: 
		rm calculator
